### ISSUE TITLE
tsconfig error

### ISSUE THREAD

**Issue by SneManden** [DanThrane/phaser-game-off#3]
I get an error in `tsconfig.json` saying that:

> Cannot write file "<path to>/Rooms/rooms.json" because it would overwrite input file.

I tried a google answer and set "noEmit": true, however this yields an error when trying to run the game anew. (Right now you can run the game with the error above, and then set noEmit to true to remove the error in the project :S)

**Comment by Ezbob** [comment]
The problem occur if you compile with the typescript compiler directly instead of using the webpack machinery (`npm run dev`). The IDE is just warning us about it. 

If you run `tsc -p .` (meaning compile using the `tsconfig.json` in the current directory), you will see that the output files are just placed where the source files are found, with this config. This causes a problem when we "compile" JSON files (such as the room files) as these are just copied around instead of being compiled to JavaScript. 

Adding a `outDir` fixes this issue as the output JSON files will be copied to that specified directory instead.

I'll put the fix up and close this.
